### ISSUE TITLE
How to Paginate result from Contact::search('john doe')

### ISSUE THREAD

**Issue by brryfrmnn** [algolia/algoliasearch-laravel#118]
How to paginate / next page from query Backend search ?
because the result just show 20 record from page 0.

**Comment by JanPetr** [comment]
Hello @brryfrmnn,

the `search()` method of your model takes as second parameter array of parameters for search. You can see the list of off all parameters in [Algolia documentation](https://www.algolia.com/doc/api-client/php/search/#search-parameters).

So if you want results from the third page, it might look like this:
```php
$result = YourModel::search('search query', ['hitsPerPage' => 20, 'page' => 2]);
```

Be careful as the page parameter is zero-based, meaning that page=0 is the first page, page=1 is the second page etc...
