### ISSUE TITLE
Is it possible to load a multi-level relationship?

### ISSUE THREAD

**Issue by petemolinero** [algolia/algoliasearch-laravel#120]
I have a parent model that has both a child and a grandchild. Here's the gist:

```
// Model *Page* has...
public function elements() {
    return $this->hasMany('App\Models\Element');
}

// Model *Element* has...
public function contents() {
    return $this->hasMany('App\Models\Content');
}

// Model *Content* has no children
```

The problem is that when I call `Page::reindex()` it's only retrieving the `Element` data--it's not diving into the `Content` data at all.

Is there any way to get all descendant relational data?

Thanks!

**Comment by chafreaky** [comment]
@petemolinero  Have you tried using the `public function getAlgoliaRecord()` method on your model and defining the array yourself by doing something like `$this->customFunction()` and having the `customFunction` build out your data how you wish?

**Comment by nexxai** [comment]
Not sure if you figured this out yet or not but if you do: 

    public function getAlgoliaRecord()
    {

        $this->contents->elements;
        return $this;

    }
    
It will work like you're expecting.

**Comment by julienbourdeau** [comment]
Thanks @nexxai and @chafreaky !
