### ISSUE TITLE
Snake Case Question

### ISSUE THREAD

**Issue by vinkla** [algolia/algoliasearch-laravel#13]
There are some variables in this project that uses `snake_case` instead of `camelCase`. Is this intentional or just for this project? In the Laravel world camelCase is preferred.

**Comment by maxiloc** [comment]
I don't see any issue for converting all variable for camelCase :)

**Comment by vinkla** [comment]
That's super!

**Comment by vinkla** [comment]
@maxiloc Awesome :+1:
