### ISSUE TITLE
Synonyms erased

### ISSUE THREAD

**Issue by maxiloc** [algolia/algoliasearch-laravel#138]
If you set synonyms via the dashboard, there is no way to not erased them
if you do a reindex.

**Comment by chafreaky** [comment]
Is there any update on this? :)

**Comment by julienbourdeau** [comment]
This won't be addressed since the project is now deprecated.

I recommend using Laravel Scout and ou [algolia settings extensions](https://github.com/algolia/laravel-scout-settings/).
