### ISSUE TITLE
Is it possible to load multiple different relationships (not simply multi-level)

### ISSUE THREAD

**Issue by nexxai** [algolia/algoliasearch-laravel#139]
Say I have a model called "Book" and that is related to both "Page" and "Author" models, but that the page and author models are separate.  If it was a simple multi-level relationship, I could do something like:

    public function getAlgoliaRecord()
    {

        $this->page->author;
        return $this;

    }
    
But since the relationships aren't related, I'm not sure how I'd go about grabbing both.  Can someone help me out here?

**Comment by acidreign** [comment]
Can't you just do this?
`public function getAlgoliaRecord()
{
    $this->author;
    $this->page;
    return $this;
}`

**Comment by nexxai** [comment]
Wow, I'm an idiot.  I figured (incorrectly) that doing $this->page; would somehow overwrite $this->author; so I didn't even bother trying.

Thank you for clearing that up for me!
