### ISSUE TITLE
Is there a way to conditionally display entire HTML tags?

### ISSUE THREAD

**Issue by nexxai** [algolia/algoliasearch-laravel#140]
This is probably another stupid question but I'm going to ask anyways.

Our index contains an optional field which if filled contains a URL to an image.  What I want to be able to do is in my template only show the entire <img tag plus the URL, etc. *if* there's an image in the image field.  If not, I want it to completely skip the <img tag altogether.

Is this possible?

**Comment by rayrutjes** [comment]
Hi @nexxai ,

This is totally do-able.

That being said, it will:
- Increase the payload sizes of your records
- Make it hard to escape the output and ensure you are secured against XSS holes

I would rather only store the image URL, and then either use an "empty image" placeholder url when no image is available, or do a condition in your frontend template.

I'm closing this for now, but feel free to add some context if my answer doesn't quite solve your issue.

**Comment by nexxai** [comment]
Thanks for the quick response - my issue is specific to the InstantSearch (which apparently I forgot to include in my original question), which makes the "condition in my frontend template" difficult from the Laravel side, I think?  I'm far from a master on JavaScript (or Laravel or PHP, for that matter) so if there's a way to do it there, I'm very interested to learn what it is, but I'm not quite sure I'd understand how to dynamically check the returned InstantSearch results to see if a particular record has an image or not.

Is this something that's possible, or am I just going to have to live with this?
