### ISSUE TITLE
Is there any way to update a record in Algolia without updating Eloquent model

### ISSUE THREAD

**Issue by kiwo12345** [algolia/algoliasearch-laravel#141]
I was wondering if there is any way to update a record in Algolia without updating my Eloquent model.
When I do `MyModal->save();` it will also update my record/row in my MySql DB. What I want to do is to update a certain row/record in my Algolia DB without updating my local MySql db.

If I set `public static $autoIndex = false;` I then have to do something like this if I want to save a record:

```
$contact = Contact::firstOrCreate(['name' => 'Jean']);
$contact->pushToIndex();
```

But is there any way I can use `pushToIndex();` to update a existing record/row in Algolia without having to update my local DB?

**Comment by julienbourdeau** [comment]
Hi @kiwo12345,

Can you give us some details about your use case? I'm interested to know why you'd like to have different information in your DB and in Algolia.

I just checked and you can use `pushToIndex()` without saving to the DB first.

```php
$people = People::find($id);
$people->name = "UPDATED";
$people->pushToIndex();
```
