### ISSUE TITLE
How to export the results from a frontend search ?

### ISSUE THREAD

**Issue by chrisvidal** [algolia/algoliasearch-laravel#142]
One of my client requirement is to add the ability to export to CSV the results of an algolia search.

How is it possible to use the the frontend query url parameter and stuffs from the backend side so I can build an export ?
I saw the method ::search but i dont see where I could use the query paramater url from the frontend

Thank you for any ideas

**Comment by julienbourdeau** [comment]
HI @chrisvidal 

Can you details what you mean by _"I saw the method ::search but i dont see where I could use the query paramater url from the frontend"_?

I believe you can use the parameters in the frontend search and the backend search:
```php
Contact::search('julien', [
    'attributesToRetrieve' => 'email',
]);
```
Are you talking about `attributesToRetrieve, `attributesToHighlight` and so on?

**Comment by chrisvidal** [comment]
Thks @julienbourdeau 
Sorry I was offline for a while.
Well, the idea is to give the user the ability to save their search with query and facet refinements.
Example: search for the query "uni" with the facet Bands value (Apple, Microsoft) and facet Color (blue, red)
I need to save this search somehow (using Laravel in my case) and then running a weekly cron job  to send the results of the saved search to the user in an email.
So i guess I am more talking about how to store this query and facet attributes, is there there a way to serialize/unserialise with the algolia php client so that I just have to save the URL ?

**Comment by julienbourdeau** [comment]
There are no built-in way to do that but it should be doable with a command.

I would save search (query, parameters, objectIDs of the X first results) in json.
Then a Laravel command would use `::search()` to replay the query and compare the results objectIDs with saved ones.

```json
{
   "model": "App\Something",
    "query": "search query string",
    "parameters": [...],
    "results": ["objectID1", "objectID2", "objectID3",...]
}
```

I hope you found a way to make it work for you.
Best,
Julien
