### ISSUE TITLE
Error handling and queues

### ISSUE THREAD

**Issue by kiwo12345** [algolia/algoliasearch-laravel#145]
I wonder if I can use some sort of error handling when using `$contact->pushToIndex();` eg `try` `catch`

Also, is it possible to use `->pushToIndex();` in a queue worker?

**Comment by julienbourdeau** [comment]
Hi @kiwo12345,

The `pushToIndex()` method should work without any problem in a queue worker.

`pushToIndex()` will call the `doRequest()` method from our PHP client so you will at least be able to catch some Algolia exceptions ([here](https://github.com/algolia/algoliasearch-client-php/blob/master/src/AlgoliaSearch/Client.php#L814) or [here](https://github.com/algolia/algoliasearch-client-php/blob/master/src/AlgoliaSearch/Client.php#L823))

**Comment by julienbourdeau** [comment]
It has been a few days since you asked the question, so if you have anything you tried and want to share, feel free to do so 😄
