### ISSUE TITLE
Using instantsearch.js, having issues with results

### ISSUE THREAD

**Issue by nexxai** [algolia/algoliasearch-laravel#163]
Ok to preface this, I am absolutely not a front-end guy so I apologize if this question is stupid. 

What I am trying to do is build a template that takes a given result and triggers some jQuery code (an AJAX request specifically) specific to that result.

For example, here is the hit-template:

```js
<div class="library-text">
    <p style="padding-left: 300px;">
        <strong>@{{screenshot.url}} @{{tour.production.title}} @{{tour.title}} - @{{date}} (@{{format.name}}):</strong> <i>CAST:</i> @{{cast}} 

        <i>NOTES: @{{notes}}</i>

        <p style="padding-left: 300px;">

            <a href="/collections/store/@{{id}}">Add to my collection</a>

             | 
            
            <span id="@{{id}}">
                <a href="#addToWant" class="iwantthis">I want this</a>
            </span>
        </p>
       
    </p>
    
</div>
```

And the goal is that if someone clicks the "I want this" link at the bottom of that result, it should trigger this AJAX request:

```js
$("a.iwantthis").mousedown(
    function() {
        var sendInfo = { 
            id: $(this).parent().attr('id')
        };

        var link = $(this);

        event.preventDefault(); 

        $.ajax({
            url: "{{ route('want.store') }}",
            method: 'POST',
            headers: { 
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            },
            datatype: 'json',
            data: sendInfo,
            success: function(response) {
                link.replaceWith('<i>Listed as want</i>');
                
            },
            error: function (xhr, ajaxOptions, thrownError) {
                alert(xhr.status + ': ' + thrownError);
            }
        })

        return false;
    }
);
```

Now the code works properly for items that already exist on the page as it's being generated and displayed, but since the results of the Algolia search don't exist in the DOM (is that the correct terminology?) until the person starts typing, I'm assuming it has something to do with those results being "new" in the eyes of jQuery.

Is there something I can do to "refresh" it, or to make jQuery see those results?

Thank you!

**Comment by julienbourdeau** [comment]
Hi Justin,
Sorry for not answering earlier. It seems like this issue is not related to this laravel pakage. I hope you have found a way to fix it.

Best,
Julien
