### ISSUE TITLE
Laravel 5.4.31

### ISSUE THREAD

**Issue by mocheaz** [algolia/algoliasearch-laravel#177]
The client can't be installed on laravel 5.4.31.

Any idea how to install it?

**Comment by rayrutjes** [comment]
Hey @mocheaz , thanks for reaching out here.
Could you be more specific?
Are you talking about the algoliasearch-client-php or this package?

Have any errors?

**Comment by mocheaz** [comment]
Sorry it was because my php wasn't ^7.0
