### ISSUE TITLE
mention “deprecation” in README

### ISSUE THREAD

**Issue by Haroenv** [algolia/algoliasearch-laravel#180]
Scout is only mentioned in the `composer.json`, not in the description or README

**Comment by rayrutjes** [comment]
![image](https://user-images.githubusercontent.com/5570853/29668151-6ebb0886-88df-11e7-88b5-0b8005f717a5.png)
First step.

Not sure if the readme is managed by one of our bots cc @julienbourdeau @maxiloc

**Comment by julienbourdeau** [comment]
Not anymore (because it's deprecated). I'll update it today 👍
