### ISSUE TITLE
Models using the Algolia trait appear broken

### ISSUE THREAD

**Issue by chrisvanderpoel** [algolia/algoliasearch-laravel#22]
If you apply an Algolia trait to a model and attempt to then call the static find() method on the model, you will receive an error.

`BadMethodCallException in Builder.php line 1992: Call to undefined method Illuminate\Database\Query\Builder::_find()`

It can be traced to the following method in the `AlgoliaEloquentTrait` trait:

```php
public static function __callStatic($method, $parameters)
{
    $instance = new static();

    $method = '_'.$method;

    if (method_exists($instance, $method));

    return call_user_func_array([$instance, $method], $parameters);

    return parent::__callStatic($method, $parameters);
}
```

This code will *always* attempt to call the method even if it might not exist due to the broken if statement.  Looks like it might have been a merge issue but even the pre-merge code would have broken due to the else scenario still attempting to call the underscore overload method.

**Comment by maxiloc** [comment]
There was also another issue fixed 9ba94a2 . Because static call inside a instance result in a non static call and therefore catch by __call and not __callStatic
