### ISSUE TITLE
Hosts unreachable: Resolving timed out after 2000 milliseconds

### ISSUE THREAD

**Issue by MarcTroesken** [algolia/algoliasearch-laravel#25]
Hi,

I´m running into this error with Laravel 5.1 when trying to index some data. Always get this error:
`AlgoliaException in Client.php line 392:`

`Hosts unreachable: Resolving timed out after 2000 milliseconds,Resolving timed out after 2000 milliseconds,Resolving timed out after 4000 milliseconds,Resolving timed out after 4000 milliseconds`

Found something similar on Twitter from 2013 but can´t figure out how to solve my problem.

Any Ideas on that ?
Thanks
Marc

**Comment by redox** [comment]
Hi Marc,

could you provide us the whole stacktrace and tell us which call triggered that? Was it a big `addObjects` or a `search` ?

**Comment by MarcTroesken** [comment]
I tried both of them. I also switched the laravel package to the original algolia_php, but same issue.
Is there a problem with indexing html ?

Here´s the long part:

![bildschirmfoto 2015-06-30 um 14 14 07](https://cloud.githubusercontent.com/assets/6149592/8430481/57fbbea6-1f32-11e5-89da-19bbdd367236.png)

**Comment by maxiloc** [comment]
Ok. It seems this is related to your php installation. Can you try to reinstall php on your environment ?

Can you also give me a bit more details on your environment so that I can try to reproduce it ?

Is it running on Window, Unix, Mac ?
Are you using something like XAMP ?

**Comment by MarcTroesken** [comment]
It is running on a virtual machine:

```bash
Ubuntu 14.04.2 LTS (GNU/Linux 3.13.0-45-generic x86_64)

PHP 5.6.8-1+deb.sury.org~trusty+1
```

**Comment by MarcTroesken** [comment]
oooouuuuh. The vm is the problem ... I pushed it to production and it worked! But do you have any ideas why ?

**Comment by maxiloc** [comment]
There is two possible explanations:
- Issue with the vm certificate (most probable)
You can check that you have certificates with this command ```ls /etc/ssl/certs | grep -i comodo```. It should return something like 5 lines. It you do not have them it means you do not have the certicates
- Issue with vm networking

I am closing this as it is not a extension related issue.

**Comment by mtilokani** [comment]
@maxiloc , I am also facing this same issue.

And when I am running command `ls /etc/ssl/certs | grep -i comodo` , then I am getting following output:

`Comodo_AAA_Services_root.pem
COMODO_Certification_Authority.pem
COMODO_ECC_Certification_Authority.pem
COMODO_RSA_Certification_Authority.pem
Comodo_Secure_Services_root.pem
Comodo_Trusted_Services_root.pem`

Can you please let me know what's the issue with this?

Thanks in advance
