### ISSUE TITLE
AutoIndex and AutoDelete will not work as documented

### ISSUE THREAD

**Issue by chrisvanderpoel** [algolia/algoliasearch-laravel#26]
The documentation is incorrect in the usage of `autoIndex` and `autoDelete`.

Based on the code...

``` php
public function isAutoIndex(Model $model)
{
    return ($this->hasAlgoliaTrait($model) && (property_exists($model, 'autoIndex') == false || $model::$autoIndex === true));
}

public function isAutoDelete(Model $model)
{
    return ($this->hasAlgoliaTrait($model) && (property_exists($model, 'autoDelete') == false || $model::$autoDelete === true));
}
```

... you *must* declare these properties as either static...

``` php
public static $autoIndex = true;
public static $autoDelete = true;
```

... or change the way you reference them in the code.  Additionally, the `property_exists` check will always fail as, if the property *does* exist on the model, `property_exists` will return `true` and you're checking against it being `false`.

``` php
public function isAutoIndex(Model $model)
{
    return ($this->hasAlgoliaTrait($model) && (property_exists($model, 'autoIndex') && $model->autoIndex === true));
}

public function isAutoDelete(Model $model)
{
    return ($this->hasAlgoliaTrait($model) && (property_exists($model, 'autoDelete') && $model->autoDelete === true));
}
```

**Comment by maxiloc** [comment]
@chrisvanderpoel Thanks. In the tests I am using static so yes the doc was wrong.

**Comment by chrisvanderpoel** [comment]
Might want to take a pass on the docs.  There are references to Ruby in there and some really confusing references to methods that do not exist in the code samples.  For instance, the `Target Multiple Indexes` section refers to an `add_index` method while the code sample below it references the `indexOnly` method.

Any particular reason you're referencing the `autoIndex` and `autoDelete` properties statically while not doing the same for other trait properties, like `perEnvironment`?  It seems like it might be cleaner to add the `autoIndex` and `autoDelete` properties to the trait and then access them in a way similar to the `perEnvironment` property.  Then you can simplify your helper methods to this:

``` php
public function isAutoIndex(Model $model)
{
    return ($this->hasAlgoliaTrait($model) && $model->autoIndex === true);
}

public function isAutoDelete(Model $model)
{
    return ($this->hasAlgoliaTrait($model) && $model->autoDelete === true);
}
```

Then you have consistency across your configuration properties.

**Comment by maxiloc** [comment]
@chrisvanderpoel Yes you are right there was some mistake on the doc, and some inconsistency regarding trait attribute. It should be good now.

The reason why we want them static is to be able to do :
```
Contact::$autoIndex = false;
Contact::clearIndices();

for ($i = 0; $i < 10000; $i++) {
    $contact = Contact::firstOrCreate(['name' => 'Jean']);
}

Contact::reindex(); // Will use batch operations.
``` 

Thanks for your help
