### ISSUE TITLE
You might want to sort the read me out...

### ISSUE THREAD

**Issue by olimorris** [algolia/algoliasearch-laravel#27]
The readme references Ruby and doesn't tell me how to search. The English is poor and so is the grammar,

As yet, I don't want to give Algolia my hard earned money or contemplate using this package in a Laravel app.

**Comment by maxiloc** [comment]
@olimorris You are right, the readme still need some work. We will work on that asap.

Also, I think I removed the last ruby reference.

**Comment by rayrutjes** [comment]
Documentation LGTM. Feel free to re-open an issue with some insights of what you'd expect us to improve.
