### ISSUE TITLE
Indexing through relationships

### ISSUE THREAD

**Issue by freddinator** [algolia/algoliasearch-laravel#28]
I have a post, and this post must have one category. The category is defined via an Eloquent relationship, so the only thing about the category on the Post model is the id. However, I want to be able to make the post searchable by category. How would I do this, even though I cannot add the category's name as an indexing parameter as it isn't actually on the Post model?

**Comment by maxiloc** [comment]
@freddinator Actually you can do it with the ```getAlgoliaRecord``` method


Here how I would do it

```
class Post extends Model
{
    use AlgoliaEloquentTrait;

    public function category()
    {
        // Relation
    }
    public function getAlgoliaRecord()
    {
        $extra_data = [
            'category' => array_map(function ($data) {
                                     return $data['name'];
                           }, $this->category->toArray())
        ];

        return array_merge($this->toArray(), $extra_data);
    }
}
```
