### ISSUE TITLE
When should I call setSettings() method on my php code?

### ISSUE THREAD

**Issue by argb** [algolia/algoliasearch-laravel#31]
Every time i push data to index ? Should I call it  on my Model class constructor?

**Comment by maxiloc** [comment]
@argb You should not call setSettings, once save from the "Algolia Search" config on wordpress admin you should be good to go

**Comment by maxiloc** [comment]
@argb I edit my last message. I made a mistake on the project.

**Comment by argb** [comment]
So that means I should not  do this on any Model logic,I should do this at outside script or by algolia web management tools,right?

**Comment by maxiloc** [comment]
Yes exactly

**Comment by argb** [comment]
@maxiloc Thank you very much.
