### ISSUE TITLE
Several bugs setting up the index

### ISSUE THREAD

**Issue by fesja** [algolia/algoliasearch-laravel#35]
Hi,

I've the following:

```
public $algoliaSettings = [
            'attributesToIndex' => [
                'title', 'categories.name', 'company.name',
                    'company.description', 'location.name'
            ],
            'customRanking' => [
                'desc(featured)',
                'desc(created_at)',
            ],
            'slaves' => [
                'jobs_home',
            ],
        ];

    public $slavesSettings = [
        'jobs_home' => [
            'ranking' => [
                'desc(featured_home)',
                'desc(created_at)',
            ]
        ]
    ];
```

Then, I do `\App\Job::setSettings();` on a command. 

1. It's creating two indexes: `jobs_local` and `jobs_home`. Shouldn't it be 'jobs_home_local`? When I upload to production it's going to be a conflict.
2. It's setting up the attributes to index and custom ranking of `jobs_local` on the slave index (`jobs_home`). And the config for `jobs_local` is empty.

I am doing something wrong or is there a bug?

regards

**Comment by maxiloc** [comment]
1.0.5 should fix your issues. Tell me how it goes

**Comment by fesja** [comment]
About the index name, you have added a bug. On ModelHelper.php:107, it should be

```
return $this->algolia->initIndex($this->getFinalIndexName($model, $index_name).'_tmp');
```

instead of

```
return $this->algolia->initIndex($this->getFinalIndexName($index_name).'_tmp');
```

The first time I set up the indexes, the settings are not saved on the main index, they are saved just on the slave. I'm going to try to locate the bug.

**Comment by maxiloc** [comment]
Yes my bad, I am fixing this

**Comment by fesja** [comment]
About the problem with saving the setting of the main index, I think it's problem of your backend. 

If I only execute ```\App\Job::setSettings();```, settings are saved on both indexes.
If I execute just after that ```\App\Job::reindex();```, petitions go well to both indexes with the correct parameters. The one to the slaved index is saved, but the one to the master index is not. This is the task ID that is going to create the settings on my master index: 2989525410. Up to now (15min later) settings haven't been created. Could you check why it hasn't been executed?

**Comment by maxiloc** [comment]
@fesja yes that is expected, if you use the reindex it will create a new index then move it. You need to do a setSettings after the reindex.

**Comment by fesja** [comment]
@maxiloc thanks! I thought reindex was just for content. It's working now.
