### ISSUE TITLE
Hosts unreachable:Resolving timed out after 2000 milliseconds

### ISSUE THREAD

**Issue by JellyBool** [algolia/algoliasearch-laravel#36]
i'm running algolia with laravel 5.1 using this package,but i got the erros when i try to index some data or setup a search.

![2015-11-08_17-36-32](https://cloud.githubusercontent.com/assets/6011686/11019692/519efb3a-863f-11e5-9368-f7592b8bf595.png)

already went throught this [issue](https://github.com/algolia/algoliasearch-laravel/issues/25),but i could not solved my problem 

running laravel 5.1 with homestead `Laravel Homestead version 2.1.6`, tried `ls /etc/ssl/certs | grep -i comodo` 

```
Comodo_AAA_Services_root.pem
COMODO_Certification_Authority.pem
COMODO_ECC_Certification_Authority.pem
Comodo_Secure_Services_root.pem
Comodo_Trusted_Services_root.pem
```

**a guy from china,any case that the internet was block by the Great Wall? because when i use my VPN connect to the internet. it works fine....**

i push it to production,still got the errors. any ideas

**Comment by asurak** [comment]
Can you give me the source IP of the requests and the APPID?

**Comment by JellyBool** [comment]
APP_ID : `9PETS208IG`;
source IP: `101.200.187.43` 

is that so?

**Comment by asurak** [comment]
Yes, perfect. The IP is Aliyun cloud in China but your Algolia account is hosted in Singapore. I recommend using the Hong Kong one as this one has much better and more stable connectivity to China. Our API is not blocked by the Great Wall as far as I know. So if possible, push your data to Hong Kong, not Singapore. I will be doing one optimization in the next few hours that will improve the latency to Aliyun from Hong Kong, but cannot do a lot from Singapore.

**Comment by JellyBool** [comment]
OK,thanks for reply...i will try it this weekend @asurak

**Comment by maxiloc** [comment]
Closing this as it is unrelated to the package. Feel free to contact us by email if needed

**Comment by chuhemiao** [comment]
@maxiloc  if ip is Aliyun ,laravel 5.1 algolia not be able to run it？

**Comment by maxiloc** [comment]
@chuhemiao Can you send an email to support at algolia dot com. We'll be happy to investigate with you
