### ISSUE TITLE
Slaves set through setSetting do not take advantage of Per-environment Indexes option

### ISSUE THREAD

**Issue by pbean** [algolia/algoliasearch-laravel#37]
Hello,

I was working on taking my granular build settings for our business out of being setup via the dashboard and configuring it all through my laravel models. However, I have discovered that the slaves feature does not take advantage of the Per-environment Indexes feature. I'm using the following format
MASTER_LOCAL
MASTER_PRODUCTION
local and production are added per the per-environment indexes feature. However if I add the following and setSettings:
'slaves' => [
            'EXAMPLESLAVENAME',
        ],
For production and local they create an index just called EXAMPLESLAVENAME. I don't want to screw anything else on my production indexes after relinking my old dashboard created slave so I haven't tested if one overwrites the slave index created based on whoever ran setsettings last but based on it not prefixing the name im going to assume it does. If this is as intended could I request it as a feature to be added or at least a $slavePerEnvironment flag to do so ? That would be greatly appreciated!!

**Comment by maxiloc** [comment]
@pbean It has been solve with release 1.0.6
Are you experiencing this with this version ?

**Comment by maxiloc** [comment]
No news I am closing this. Feel free to re-open if needed
