### ISSUE TITLE
autoIndex and autoDelete do not works on Eloquent builders

### ISSUE THREAD

**Issue by RomainSauvaire** [algolia/algoliasearch-laravel#41]
Hello,

When I trigger updates and deletes from the Eloquent builder, the Algolia indexes are not touched :
**This doesn't work**
```
Ad::where('id', $adId)->update($attributes);
```
**This does work**
```
Ad::find($adId)->update($attributes);
```
I have the same problem with the `delete()` method.

What am I missing here and why is it working only with Models : this forces me to do two requests `find()` + `update()` rather than only one `update()`.

**Comment by maxiloc** [comment]
@RomainSauvaire yes

```
Ad::where('id', $adId)->update($attributes);
```

is not an Eloquent call, it is just a convenient way to generate the query hidden behind the model, so yes it's expected

**Comment by RomainSauvaire** [comment]
Hello @maxiloc 
I understand your answer but I would advice you to state it in the documentation since this is a big "weakness" and would avoid a lot of googling for other people.

**Comment by maxiloc** [comment]
@RomainSauvaire Thanks for the feedback, I added a block about this => 1f1351f

**Comment by RomainSauvaire** [comment]
Big thank you :+1:
