### ISSUE TITLE
Where's before indexing

### ISSUE THREAD

**Issue by xitude** [algolia/algoliasearch-laravel#43]
I'm trying to index my dataset but i only want the data with the status of 1.
How would I achieve that because current efforts are not working.

````php
$products = Product::where('status', 1)->reindex()->get();
        //$products->reindex();
        Product::setSettings();
        $count = count($products);
        return $count.' products sync\'d to Algolia';
``````
"Call to undefined method Illuminate\Database\Query\Builder::reindex()"

**Comment by maxiloc** [comment]
Yes there has been the question multiple times that why we added this section in the readme => https://github.com/algolia/algoliasearch-laravel#eloquent-compatibility

You need to fetch everything before pushing the data, something like:

```
$products = Product::where('status', 1)->get();
Product::setSettings();
foreach ($products as $product) {
  $product->reindex();
}
```

**Comment by xitude** [comment]
My apologies, I did look but was unable to find anything. Thank you for your assistance.

**Comment by maxiloc** [comment]
no worry :smile:, I will add a example for collection as it is missing from the readme

**Comment by xitude** [comment]
After 10 mins of trying this, all i can say is it takes ages and doesn't complete. I had 500+ rows to index and it timed out.

**Comment by maxiloc** [comment]
Did you had a look at https://github.com/algolia/algoliasearch-laravel#restrict-indexing-to-a-subset-of-your-data if that fit your use case you calling Product::reindex(); will batch everything automatically ?

**Comment by xitude** [comment]
I think it's safe to assume i'm blind and not paying attention to anything in the docs.
Ill give it a go and get back to you.
