### ISSUE TITLE
algoliaSettings

### ISSUE THREAD

**Issue by xitude** [algolia/algoliasearch-laravel#44]
Where can I find a full list of settings I can apply to indexes?
Im currently looking for Query words interpretation setting.

**Comment by xitude** [comment]
I found them on the ?'s on the site.

**Comment by Jerskouille** [comment]
You have a full list of [indexing parameters](https://www.algolia.com/doc/php#indexing-parameters) in the PHP doc, alongside [query parameters](https://www.algolia.com/doc/php#query-parameters).
