### ISSUE TITLE
AlgoliaEloquentTrait error in __callStatic method

### ISSUE THREAD

**Issue by fahad-softpyramid** [algolia/algoliasearch-laravel#45]
I just figure out a minor issue in __callStatic method() method of "AlgoliaEloquentTrait".
I think the if condition at line 193 should be replaced by following because it prevents all Eloquent methods to be called:

if (method_exists($instance, $method)){
            return call_user_func_array([$instance, $method], $parameters);
}else{
            $method = str_replace("_","",$method);
            return parent::__callStatic($method, $parameters);
}

**Comment by maxiloc** [comment]
@fahad-softpyramid 

Are you using the last version ?
Because we don't have this issue with the last one
https://github.com/algolia/algoliasearch-laravel/blob/master/src/AlgoliaEloquentTrait.php#L197

**Comment by fahad-softpyramid** [comment]
I did use the latest version. But thanks for fixing ;)

**Comment by maxiloc** [comment]
I did not fix anything :smile:, that why I was asking

**Comment by fahad-softpyramid** [comment]
Yeah I think that was the 1.0@dev version. Thanks for help though.
