### ISSUE TITLE
Insert all data at once

### ISSUE THREAD

**Issue by prspace** [algolia/algoliasearch-laravel#46]
Can anyone please tell me how can i insert all table rows at once like in "algolia-php" library $algolia->saveObject($rows);

**Comment by maxiloc** [comment]
@prspace Can you give me a bit more context on what you are trying to achieve ?

**Comment by prspace** [comment]
All i want to do is suppose i have a model 'Listing'. Now is i want to save it to algolia index i have to do 
$listing = Listing::find(1);
$listing->pushToIndex();
If i have many listings it takeing too much time to push all of them.

And i need like that Listing::all()->pushToIndex();

**Comment by prspace** [comment]
Is this package compatible for laravel 5.1

**Comment by maxiloc** [comment]
Yes it's compatible with 5.1

you can use the reindex method.

```php
Listing::reindex();
```

**Comment by prspace** [comment]
Thanks for helping me. Can you please tell me how can i do Listing::reindex() with relationships like Listing::with('uploads')->reindex();

**Comment by maxiloc** [comment]
this is not yet possible, it's part of https://github.com/algolia/algoliasearch-laravel/issues/47
