### ISSUE TITLE
Indexing many records with relationships

### ISSUE THREAD

**Issue by florentdouine** [algolia/algoliasearch-laravel#47]
Hi !

I'm trying to index many rows of my database (about 20000) in Algolia, so i tried 2 solutions : 
• Class:reindex() make 4 or 5 SQL queries for every rows so it takes a very long time to fetch all datas.
• Object->pushToIndex() after i fetch datas from database but it seems to take a long time to send data to Algolia server.

Is there a solution for my case ?

**Comment by maxiloc** [comment]
I would copy this method and rename it to ```reindex```

And replace

```
static::chunk(100, function ($models) use ($indicesTmp, $modelHelper) {
```

by

```
static::with('relation1', 'relation2')->chunk(100, function ($models) use ($indicesTmp, $modelHelper) {
```

I think we should add to way to handle that better. I will try to do that this week

**Comment by florentdouine** [comment]
It's exactly what i'll need, thanks for your work !
