### ISSUE TITLE
Cannot add object when Model ID is binary

### ISSUE THREAD

**Issue by gervye** [algolia/algoliasearch-laravel#48]
The ID of my table is a binary UUID. The Algolia traits throws a 400 exception when saving a model instance and I see that it calls an API entry with a bad path:
AlgoliaException in Client.php line 562:
400 in Client.php line 562
at Client->doRequest(object(ClientContext), 'PUT', 'LTNCXQAANN.algolia.net', '/1/indexes/blbm_me/%11%E5%C1%1A%E9%3B%84%E0%84X%00%11%223DU' ...

Note that setting the $autoIndex = false and using the pushToIndex() method is working well to save the model.

I think that the problem is coming from the EloquentSubscriber.php file, function saved():
$index->addObject($this->modelHelper->getAlgoliaRecord($model), $this->modelHelper->getKey($model));
It uses the getKey() function which returns the raw binary ID and may be it should use the getObjectId() function as I set the $objectIdKey variable in the model to the name of the computed field containing the "stringified" version of the ID.

.

**Comment by maxiloc** [comment]
yes indeed there is an issue, let me fix this

**Comment by maxiloc** [comment]
Fixed with 5d176ceda0b55b4a87416808b90465190cf8d9de
