### ISSUE TITLE
Setting distinct for an index by default using $algoliaSettings

### ISSUE THREAD

**Issue by walteranderson** [algolia/algoliasearch-laravel#54]
Greetings,

I have a model set up to automatically sync to Algolia and for this index I would like to have the field called `category` to be distinct by default for all queries. In my Eloquent model, part of my `$algoliaSettings` look like this:

```
public $algoliaSettings = [
    'attributeForDistinct' => 'category'
];
```

When I call `Model::setSettings()` and then take a look at the index display settings in the web app, I see this:

![screen shot 2016-03-16 at 9 43 32 am](https://cloud.githubusercontent.com/assets/5472182/13816269/adac9ea6-eb5b-11e5-8230-bbea616d21ee.png)

The distinct true/false option is not set. I have looked through the documentation here and on Algolia and cannot find anything that will allow me to programmatically set distinct to true for all queries. Does this feature exist? And do you know of any way I can mark distinct as true without logging in and manually setting it each time I need to update the index settings?

Thanks for the help!

**Comment by maxiloc** [comment]
Did you try:

```
public $algoliaSettings = [
    'attributeForDistinct' => 'category',
    'distinct' => true
];
```
?

**Comment by walteranderson** [comment]
Excellent! Thank you very much. I'm not sure how I managed to try every variation except for this one, but I do appreciate the help.

I suppose when I was looking through the documentation, I was expecting `$algoliaSettings` to only include indexing parameters and the only examples I could find using the distinct option were at the query level.
