### ISSUE TITLE
Index subset & add to index

### ISSUE THREAD

**Issue by JapSeyz** [algolia/algoliasearch-laravel#55]
Hey.

Is it possible to add to the indexed subset of data?

Eg. I would like to add $user->name to my subset of data as user_name, this is to prevent having to load the entire user model on every single search which shows this data.

Let's say my model contains these attributes:
[
'id' => int,
'name' => str,
'email' => str
]

I don't want the email to be searchable, therefore I'll set the data to return a subset, in this case it's just the name.

now we have:
[
'id' => int,
'name' => str
]

Lastly, I would like to add a single relationship attribute to this data and end up with:
[
'id' => int,
'name' => str,
'emergency_contact' => $this->contact->name
]

Finally, index this data, possible?

**Comment by maxiloc** [comment]
By default the package use the Laravel toArray() method which already take into account $hidden, $visible and $appends properties.

If you want something more custom you can create an ```getAlgoliaRecord``` method and arrange the record how you want it.

Check the readme for examples.

**Comment by JapSeyz** [comment]
Alright thanks.

Could you give me a quick example of "Restrict Indexing to a Subset of Your Data", because the example given doesn't make a lot of sense to me, except if you have to setup an array of values inside the method body.

**Comment by maxiloc** [comment]
Let's say you want to index users that have more than 10 friends
```php
use Illuminate\Database\Eloquent\Model;

class User extends Model
{
    use AlgoliaEloquentTrait;

    [...] // friends relationship

    public function indexOnly($index_name)
    {
        return (bool) $this->friends > 10;
    }
}
```

**Comment by JapSeyz** [comment]
Ahh, I thought I could pick and choose individual columns like that, I see now that it is meant for pick and choosing rows instead.
