### ISSUE TITLE
Disabling for Testing

### ISSUE THREAD

**Issue by jschutt** [algolia/algoliasearch-laravel#57]
Thank you all for your work on this package! It's much appreciated.

Is there a good way to disable the package when running tests? I'm migrating and seeding my database when I run my tests, and the package is attempting to push the data to Algolia every time a model is saved.

What do you think?

**Comment by maxiloc** [comment]
I would set the following static attributes to false:
- autoIndex
- autoDelete

**Comment by jschutt** [comment]
Thank you @maxiloc - That does speed up the tests. 

Is there a way to dynamically set that static variable though? I would like it to be false if the current environment is `testing` and true otherwise.

**Comment by maxiloc** [comment]
Yep. That something we could add

**Comment by maxiloc** [comment]
@jschutt #57 will fix it
