### ISSUE TITLE
Update relationships

### ISSUE THREAD

**Issue by JapSeyz** [algolia/algoliasearch-laravel#60]
Hello.

How I update relationship data once that relationship has been updated?

Eg. I have a car with a passenger relationship. I load the passenger into Algolia along with the car, but whenever the passenger is updated, nothing happens to the Car index where the passenger is also loaded.

It cannot be correct that I have to reindex everything every time.

**Comment by maxiloc** [comment]
@JapSeyz This is something that we can not handle in a generic way.

The extension relies on eloquent save event to update in algolia.
When you save a passager model laravel will never trigger a save event on the car model.

Even if we would trigger it manually, there is no guaranty that relationships of the passager model would be loaded + there is no way in laravel to tell that a relationship in one model is the opposite relationship on another model.

The quick fix for you would be to listen for the save event of the passenger model, and trigger a reindex of the car in case it's fired.

**Comment by florentdouine** [comment]
Maybe this can help : https://laravel.com/docs/5.2/eloquent-relationships#touching-parent-timestamps

It's just an idea but maybe you can touch 'car' entity every time you change a passenger (update the field date_updated). Maybe it will force reindex on Algolia

**Comment by JapSeyz** [comment]
@florentdouine Thanks.
I ended up extending _reindex() with an additional parameter where I can pass in the rows that I wish to reindex.

Then from the Car, I simply get all the Passengers but leave every other Human alone, and pass the Passenger rows into the _reindex function.

**Comment by maxiloc** [comment]
This is not something we can do on our side because we don't have the knowledge about relationship

**Comment by JapSeyz** [comment]
I know, I was saying it was what I ended up doing.

**Comment by maxiloc** [comment]
@JapSeyz I was responding to @florentdouine 😄

**Comment by JapSeyz** [comment]
@maxiloc ohhh 😂
