### ISSUE TITLE
Anyway Not To Index A Particular Record?

### ISSUE THREAD

**Issue by lesterchan** [algolia/algoliasearch-laravel#65]
I am using getAlgoliaRecord() to create a custom structure in my model

I am wonder is there anyway I can break out of this function aka not index to algolia if for example a record is not public?

I tried
```
if ($status !== 'public' ) {
return null;
}
```
But the record still got pushed

**Comment by JanPetr** [comment]
Hi @lesterchan,

there is available filter method `indexOnly()` - https://github.com/algolia/algoliasearch-laravel#restrict-indexing-to-a-subset-of-your-data

In your case it might look like this:
```php
public function indexOnly($indexName)
{
    return $this->status === 'public';
}
```

Does it help?

**Comment by lesterchan** [comment]
Perfect! Thanks @JanPetr. I totally miss that portion of the doc!
