### ISSUE TITLE
Legacy site with hard coded () in URLs

### ISSUE THREAD

**Issue by sunscreem** [algolia/algoliasearch-laravel#71]
I'm working on a legacy site and it has has products with urls with bracket in:

[https://kiltmakers.co.uk/products/scottish-gifts/pocket-watches-and-clocks/2-piece-thistle-gift-set-(pocket-watch-and-cufflinks)](https://kiltmakers.co.uk/products/scottish-gifts/pocket-watches-and-clocks/2-piece-thistle-gift-set-(pocket-watch-and-cufflinks))

Not ideal.

I'm using Laravel to upload the index to Algolia but its stripping out the brackets so the resultant url is:

https://kiltmakers.co.uk/products/scottish-gifts/Pocket%20Watches%20and%20Clocks/2-piece-thistle-gift-set-pocket-watch-and-cufflinks

Which gives a 404.

I've tried using url_encoding on the urls but that strips out all the dash - I just keep making things worse! Any suggestions for how I can get Laravel and Algolia to play nicely with the brackets?

**Comment by sunscreem** [comment]
Turns out brackets are not valid in urls. So I removed the offending legacy code.

**Comment by maxiloc** [comment]
Sorry for not responding, we missed this issue. Glad you were able to fix your issue. Feel free to ping us if you have any question.
