### ISSUE TITLE
Fail to reindex an index with slave

### ISSUE THREAD

**Issue by mythsam** [algolia/algoliasearch-laravel#72]
Getting exception when calling reindex():

 [AlgoliaSearch\AlgoliaException]
  A slave index is already slave of another index

It appear to be calling setSettings() before unsetting the "slaves" key

>             if (count(array_keys($settings)) > 0) {
>                 $index->setSettings($settings);
>             }
> 
>             if ($b && isset($settings['slaves'])) {
>                 $b = false;
>                 unset($settings['slaves']);
>             }

Please review this issue.

**Comment by maxiloc** [comment]
Yes this is intended because we want to set the slaves for the first index of getIndices. I think it can happen when modifying the slaves name between classes. The easiest way to go is to delete slaves indices from the algolia dashboard

**Comment by maxiloc** [comment]
Can you tell me if that fixes your issue
