### ISSUE TITLE
How to send multiple queries?

### ISSUE THREAD

**Issue by tanshiqi** [algolia/algoliasearch-laravel#80]
Just like: https://www.algolia.com/doc/api-client/php/search#multiple-queries
I didn't see multipleQueries method in Laravel Package. How to do this? 
Thanks

**Comment by maxiloc** [comment]
@tanshiqi Sorry for the delay. You need to use the php client that is installed with the algoliasearch-laravel package.

We use the great vinkla/algolia package that is the bridge between the algolia client and laravel.
See https://github.com/vinkla/laravel-algolia to know how to use it
