### ISSUE TITLE
Algolia Tags

### ISSUE THREAD

**Issue by kinnedev** [algolia/algoliasearch-laravel#82]
Is there a way to add a tag to an Object when saving it to Algolia. 

For examples I have users with a state relationship. I would like to save a tag depending on that relationship. 

Then I can search by query and tag on the front end. 

Thank You!

**Comment by maxiloc** [comment]
Hi @kinnedev,

Yes you can implement the `getAlgoliaRecord` method on your model:

```
public function getAlgoliaRecord()
{
  $tags = FIXME; // compute your tags
  return array_merge($this->toArray(), [
    '_tags' => $tags
  ]);
}
```

**Comment by kinnedev** [comment]
Awesome!

So I can run this method on any create or update correct?

**Comment by maxiloc** [comment]
Yes any create or update will call this method to generate the record

**Comment by kinnedev** [comment]
Great! Thanks for the quick replies!
