### ISSUE TITLE
Issue with Geolocation data (lat / lng) indexing

### ISSUE THREAD

**Issue by luan0508** [algolia/algoliasearch-laravel#83]
Geo-search overview expects geoloc array with lat and lng values.

How can I index in my database a geoloc array ? Should I store as string? Create a relational table called _geoloc? Use mySQL spatial point column?

[
 {
    objectID: "3797",
    name: "John F Kennedy Intl",
    city: "New York",
    country: "United States",
    iata_code: "JFK",
    _geoloc: {
      lat: 40.639751,
      lng: -73.778925
    },
    links_count: 911
  },
  // […]
]

**Comment by luan0508** [comment]
can someone please help?

**Comment by maxiloc** [comment]
Sorry for the response delay.
Do you still have the issue ?

**Comment by luan0508** [comment]
hi @maxiloc, yes I haven't been able to resolve this issue. Do you have any suggestions on how to store _geoloc data?

**Comment by maxiloc** [comment]
The `getAlgoliaRecord` code should look like:

```
public function getAlgoliaRecord()
{
    return array_merge($this->toArray(), [
        '_geoloc' => [
            "lat" => $this->geoloc_lat,
            "lng" => $this->geoloc_lng
        ]
    ]);
}
```

`$this->geoloc_lat` and `$this->geoloc_lng` should be replaced by the code needed to fetch latitude and longitude depending on how your store your geoloc data
