### ISSUE TITLE
Can you limit attributes (table columns) uploaded to Algolia?

### ISSUE THREAD

**Issue by kdoonboli** [algolia/algoliasearch-laravel#84]
For example, I may have 12 columns in my model/table, but I only want to upload 3 attibutes uploaded to Algolia?.
I understand I can set "searchable attributes" to limit which attributes are searched, but still all 12 attributes/table columns get uploaded to Alogolia.

**Comment by maxiloc** [comment]
You can implement the `getAlgoliaRecord` method on your model, it will look like this:

```
public function getAlgoliaRecord()
{
    return [
        'attr1' => $this->attr1,
        'attr2' => $this->attr2,
        'attr3' => $this->attr3,
    ];
}
```

**Comment by kdoonboli** [comment]
Thanks!! It worked.
It would be helpful to add this to the Read Me section.

**Comment by maxiloc** [comment]
Yes the readme needs some love right now. We'll do a new iteration very soon.

**Comment by maxiloc** [comment]
Thanks for the feedback 💯
