### ISSUE TITLE
Reindex Data with Relational Table

### ISSUE THREAD

**Issue by naumanahmed19** [algolia/algoliasearch-laravel#88]
I have implemented Aloglia (laravel scout.) for my Movies table with actors as relational table and it works fine.

Problem:

When I update any movie its also updating algolia index (its good). But how can I update index if I made any change in relational table (for example update an actor of movie).

How to push a specific record manually with laravel scout.

Right now follwoing code is reindex all movies once i update any actor but its missing relational table actor althogh I have ```toSearchableArray```  in Movies model

Actor Controller Update Method
```
public function update(Actor $actor,Request $request){
	$actor->fill($request->all())->save();
	Movie::reindex();
}

```
In my Movie model 

```

    public function toSearchableArray(){
		$extra_data = [];
		$extra_data['actors'] = array_map(function ($data) {
		     return [
                            'name' => $data['name'],
                             'age' =>$data['age']
                      ];
		}, $this->actors->toArray());
		
	        return array_merge($this->toArray(), $extra_data);
	}

```
and if I run 
``` php artisan  scout:import "App\Movie"  ```
everything work properly ...

**Comment by naumanahmed19** [comment]
I got it working by changing ```toSearchableArray```to ```getAlgoliaRecord`` 

Now I am wondering is it ok to use ```Movie::reindex();```  because its updating all records. or should I use ```indexOnly``` and how

**Comment by maxiloc** [comment]
@naumanahmed19 I am closing this. This issue should be directed to the laravel/scout repo.
Feel free to contact us via email for scout related support (support at algolia dot com)
