### ISSUE TITLE
indexOnly() indexname how to write

### ISSUE THREAD

**Issue by LarsWith** [algolia/algoliasearch-laravel#89]
I was looking at this func

```
public function indexOnly($index_name)
{
        return (bool) $condition;
}
```

But how do i write $index_name?

is it

public function indexOnly("myIndexName")
{
        return (bool) $condition;
}

or

public function indexOnly(['myIndexName'])
{
        return (bool) $condition;
}

Also if I run save() on my model it will reindex.

But can I disable the index for a one time save only or must I use indexOnly() ?

**Comment by JanPetr** [comment]
Hello @LarsWith,
your don't have to pass the `$indexName` manually. It's a variable and it's passed to the method automatically, so you can use it for the condition if the record should or should not be indexed.

You can just add this to your model:
```php
public function indexOnly($indexName)
{
    var_dump($indexName);

    return true;
}
```
and reindex. And you should see the name of the index printed out.

When you call `save()` on your model it should index only saved record. But you can take a look on [auto-indexing mechanism](https://github.com/algolia/algoliasearch-laravel#auto-indexing--asynchronism) and find the best way that fits you.
