### ISSUE TITLE
Index prefixes

### ISSUE THREAD

**Issue by joshforbes** [algolia/algoliasearch-laravel#90]
Does any besides me have a use case for dynamically setting prefixes on indexes? We run multiple sites out of one codebase with some key differences being decided by a site variable in the .env.  With the index being set through a property I cannot use an expression (such as config('algolia.index-prefix')) to set it.

This could be accommodated with a  fairly simple change to the code base.  Simply changing the getFinalIndexName() method to the following (or similar):

```
public function getFinalIndexName(Model $model, $indexName)
{
    $index_prefix = method_exists($model, 'getPrefix') ? $model->getIndexPrefix().'_' : '';
    $env_suffix = property_exists($model, 'perEnvironment') && $model::$perEnvironment === true ? '_'.\App::environment() : '';

    return $index_prefix.$indexName.$env_suffix;
}
```

If the maintainers are interested in adding this I can submit a pull request.

Thanks!

**Comment by joshforbes** [comment]
Alternatively, instead of a method to get the index prefix there could be a indexes() method that allowed the indexes to be set in a method.

**Comment by joshforbes** [comment]
I possible implementation would be:

https://github.com/algolia/algoliasearch-laravel/pull/91

**Comment by julienbourdeau** [comment]
Thanks for your PR :)
