### ISSUE TITLE
Prevent getAlgoliaRecord() from getting called every time I use update() or save()

### ISSUE THREAD

**Issue by kiwo12345** [algolia/algoliasearch-laravel#93]
Is there a way to prevent `getAlgoliaRecord()` from getting called each time I use `save()` or `update()` ?

Sometimes I update my records by using ->save() and ->update() and this seems to trigger the `getAlgoliaRecord()` function

**Comment by GiampaoloFalqui** [comment]
You can find more information about disabling automatic indexing here.

https://github.com/algolia/algoliasearch-laravel#auto-indexing--asynchronism
